services:
  daikon_chem_vault_api:
    build: .
    volumes:
      - .:/app
    ports:
      - "10001:10001"
    env_file:
      - .env
    environment:
      CHEMVAULT_DATABASE_URL: ${CHEMVAULT_DATABASE_URL}
      CHEMVAULT_LOG_LEVEL: ${CHEMVAULT_LOG_LEVEL}
      CHEMVAULT_LOG_JSON: ${CHEMVAULT_LOG_JSON}
    # depends_on:
    #   - daikon_chem_vault_db

    networks:
      - daikon-be-net

networks:
  daikon-be-net:
    external: true
    name: daikon-be-net