services:
  daikon_chem_vault_db:
    image: informaticsmatters/rdkit-cartridge-debian:Release_2024_03_3
    restart: always
    environment:
      CHEMVAULT_POSTGRES_USER: ${CHEMVAULT_POSTGRES_USER}
      CHEMVAULT_POSTGRES_PASSWORD: ${CHEMVAULT_POSTGRES_PASSWORD}
      CHEMVAULT_POSTGRES_DB: ${CHEMVAULT_POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    networks:
      - daikon-be-net


volumes:
  postgres_data: