version: '3.9'

services:
  daikon_chem_vault_db:
    #image: postgres:15
    image: informaticsmatters/rdkit-cartridge-debian:Release_2024_03_3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    
    networks:
      - daikon-be-net

  daikon_chem_vault_api:
    build: .
    #command: pipenv run uvicorn app.main:app --host 0.0.0.0 --port 10001
    volumes:
      - .:/app
    ports:
      - "10001:10001"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_JSON: ${LOG_JSON}
    depends_on:
      - daikon_chem_vault_db

    networks:
      - daikon-be-net

volumes:
  postgres_data:

networks:
  daikon-be-net:
    external: true
    name: daikon-be-net