"""Create a baseline migrations

Revision ID: 954ae51c957f
Revises: 
Create Date: 2024-08-26 14:24:21.163405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954ae51c957f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molecules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('formula', sa.String(), nullable=True),
    sa.Column('molecular_weight', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_molecules_id'), 'molecules', ['id'], unique=False)
    op.create_index(op.f('ix_molecules_name'), 'molecules', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_molecules_name'), table_name='molecules')
    op.drop_index(op.f('ix_molecules_id'), table_name='molecules')
    op.drop_table('molecules')
    # ### end Alembic commands ###
