"""pains_table

Revision ID: e442c0029ef0
Revises: 6acae52c0ea4
Create Date: 2025-02-28 13:02:50.076538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e442c0029ef0'
down_revision: Union[str, None] = '6acae52c0ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rdkit_pains', sa.Boolean(), nullable=False),
    sa.Column('rdkit_pains_label', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('_created_by', sa.UUID(), nullable=True),
    sa.Column('_updated_by', sa.UUID(), nullable=True),
    sa.Column('_deleted_by', sa.UUID(), nullable=True),
    sa.Column('_is_deleted', sa.Boolean(), nullable=True),
    sa.Column('_status', sa.String(), nullable=True),
    sa.Column('_version', sa.Integer(), nullable=True),
    sa.Column('_owner_id', sa.UUID(), nullable=True),
    sa.Column('_tenant_id', sa.UUID(), nullable=True),
    sa.Column('_tags', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['molecules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pains_id'), 'pains', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pains_id'), table_name='pains')
    op.drop_table('pains')
    # ### end Alembic commands ###
